### ISSUE TITLE
Transformer output type cannot be specified

### ISSUE THREAD

**Issue by ktk** [fusepoolP3/p3-dashboard#14]
I was really confused that after my tests with BatchRefine all transformed files were the same like the input file. This is because I cannot specify the input type and default in BatchRefine seems to be CSV. Currently the requested Accept-header is `*/*`so BatchRefine technically does it right I think.

I would propose that transformers should in this case output RDF as this is the main goal of P3 but we also need to be able to specify the output type in the widget UI.

**Comment by retog** [comment]
The transforming container API https://github.com/fusepoolP3/overall-architecture/blob/master/transforming-container-api.md doesn't provide an option to define the output type. I would suggest you raise an issue against BatchRefine so that it uses another default output format. I'm surprised that the configuration doesn't define that the output is RDF.

Closingthe issue as it definitively cannot be addressed in the dashboard as long as there is no backend support.

**Comment by ktk** [comment]
Ok but transformers can have multiple output types which they support, shouldn't it be possible to set the Accept header then?
